Repository jfrog/jfrog-client-go, pull requests merged in 2022-10, with the labels that each got.

#661 feat: Add swift support for local remote virtual and federated repos
  README.md
  artifactory/services/federatedrepository.go
  artifactory/services/localrepository.go
  artifactory/services/remoterepository.go
  artifactory/services/virtualrepository.go
  tests/artifactoryfederatedrepository_test.go
  tests/artifactorylocalrepository_test.go
  tests/artifactoryremoterepository_test.go
  tests/artifactoryvirtualrepository_test.go
Labels: new feature

#663 Fix reference token error hint
  auth/authutils.go
Labels: improvement

#666 Fix converting local pattern to Regexp on windows
  utils/io/httputils/pollingexecutor.go
  utils/utils.go
  utils/utils_test.go
Labels: bug

#668 Improve server getVersion error response
  artifactory/services/system.go
  distribution/services/version.go
  pipelines/services/system.go
  xray/services/version.go
Labels: improvement
