Repository jfrog/jfrog-client-go, pull requests merged in 2022-05, with the labels that each got.

#560 Missing npm dependencies may return an error
  go.mod
  go.sum
Labels: safe to test

#561 Redirect log.Output if needed
  utils/log/logger.go
Labels: safe to test, ignore for release

#562 Upgrade build info go to v1.2.6
  go.mod
  go.sum
Labels: bug

#565 Upgrade the golang.org/x/crypto depedency
  go.mod
  go.sum
Labels: bug, safe to test

#564 Move git execute functionality
  utils/git.go
  utils/git_test.go
Labels: safe to test

#563 New Artifactory export service
  README.md
  artifactory/emptymanager.go
  artifactory/manager.go
  artifactory/services/export.go
  tests/artifactoryexport_test.go
Labels: safe to test, new feature

#566 Removed ability for the Logger to be nil and require a panic
  utils/log/logger.go
Labels: safe to test

#572 Fix git execution function wrong path assignment
  utils/git.go
Labels: bug, safe to test
