Repository jfrog/jfrog-client-go, pull requests merged in 2022-09, with the labels that each got.

#644 Add Cpes field to component struct
  artifactory/services/utils/aqlquerybuilder.go
  go.mod
  go.sum
  tests/distribution_test.go
  tests/xraywatch_test.go
  utils/io/fileutils/files.go
  xray/services/scan.go
Labels: new feature

#643 Make DeactivateKeyEncryption return wasEncrypted
  README.md
  artifactory/emptymanager.go
  artifactory/manager.go
  artifactory/services/system.go
  tests/artifactorysystem_test.go
Labels: breaking change

#647 Allow stopping retry executor
  http/httpclient/client.go
  utils/retryexecutor.go
  utils/retryexecutor_test.go
Labels: improvement

#646 Sync-deletes - The wrong folders are deleted when uploading files with uppercase names
  artifactory/services/utils/deleteutils.go
  artifactory/services/utils/searchutil.go
  artifactory/services/utils/tests/testdata/candidate_dirs_to_be_deleted_results.json
Labels: bug

#648 Generate Vulnerabilities Report - correct the location of key "include_path_pattern"
  xray/services/report.go
Labels: bug

#650 Improve bugs reporting view to Github's new Issue Form UI
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: ignore for release

#651 Fix JFrog Pipelines tests
  tests/accessproject_test.go
  tests/pipelinesintegrations_test.go
  tests/utils_test.go
  tests/xraywatch_test.go
Labels: ignore for release

#649 Transfer files - Report transfer files usage
  artifactory/usage/reportusage.go
  artifactory/usage/reportusage_test.go
Labels: new feature

#656 Add hint for for Identity/Reference Tokens errors
  auth/authutils.go
Labels: improvement

#655 Update ssh-agent package version for windows bug
  go.mod
  go.sum
Labels: bug

#652 Upload - Return summary upload results in case of upload failure
  artifactory/manager.go
  artifactory/services/upload.go
  tests/artifactoryupload_test.go
  tests/testdata/upload/folder1/file1
  tests/testdata/upload/folder2/file2
Labels: bug
