Repository jfrog/jfrog-client-go, pull requests merged in 2022-12, with the labels that each got.

#673 Add external dependencies rewrite parameters for helm remote repos
  artifactory/services/remoterepository.go
  tests/artifactoryremoterepository_test.go
Labels: improvement

#682 Upgrade build-info-go to v1.8.4
  go.mod
  go.sum
Labels: ignore for release

#678 Can't upload a directory if its name includes '()'
  artifactory/services/upload.go
  artifactory/services/upload_test.go
  utils/parenthesesutils.go
  utils/parenthesesutils_test.go
  utils/utils.go
  utils/utils_test.go
Labels: bug

#662 Upload - Take into account the repository name with exclude pattern and include directory flags
  artifactory/services/fspatterns/utils.go
  artifactory/services/fspatterns/utils_test.go
  artifactory/services/upload.go
  artifactory/services/upload_test.go
  artifactory/services/utils/artifactoryutils.go
  artifactory/services/utils/artifactoryutils_test.go
  tests/artifactoryupload_test.go
Labels: bug

#677 Added run service to pipelines
  README.md
  pipelines/manager.go
  pipelines/services/resource.go
  pipelines/services/run.go
  pipelines/services/sync.go
  pipelines/services/syncstatus.go
  pipelines/services/types.go
  pipelines/services/utils.go
  tests/jfrogclient_test.go
  tests/pipelinesrun_test.go
  tests/utils_test.go
Labels: new feature

#684 Make tests run sequentially
  utils/tests/utils.go
Labels: ignore for release

#685 Inspect hardlinks before unarchive
  utils/io/fileutils/archive.go
  utils/io/fileutils/archive_test.go
  utils/io/fileutils/testdata/zipslip/hardlink-tilde.tar
  utils/io/fileutils/testdata/zipslip/hardlink-tilde.tar.gz
Labels: improvement

#686 Add .frogbot/frogbot-config.yml
  .frogbot/frogbot-config.yml
Labels: ignore for release
