Repository jfrog/jfrog-client-go, pull requests merged in 2022-08, with the labels that each got.

#596 feat(get-all-groups): Add Client API to get all groups from Artifactory
  README.md
  artifactory/services/groups.go
  tests/artifactorygroup_test.go
Labels: safe to test

#625 Improve Platform version logs and fix groups Lint issue
  artifactory/auth/rtdetails.go
  artifactory/services/groups.go
  distribution/auth/dsdetails.go
  pipelines/auth/pipelinesdetails.go
  pipelines/services/system.go
  xray/auth/xraydetails.go
Labels: ignore for release

#627 Unarchive fail with legit symlinks
  utils/io/fileutils/archive.go
  utils/io/fileutils/archive_test.go
  utils/io/fileutils/testdata/archives/softlink-rel.tar
  utils/io/fileutils/testdata/archives/softlink-rel.tar.gz
  utils/io/fileutils/testdata/archives/softlink-rel.zip
  utils/io/fileutils/testdata/zipslip/softlink-rel.tar
  utils/io/fileutils/testdata/zipslip/softlink-rel.tar.gz
  utils/io/fileutils/testdata/zipslip/softlink-rel.zip
Labels: safe to test

#628 Improve server response log
  utils/errorutils/errorutils.go
Labels: ignore for release

#630 Fix flaky StorageInfo test
  artifactory/services/utils/storageutils.go
  artifactory/services/utils/storageutils_test.go
  tests/artifactorystorage_test.go
Labels: safe to test, ignore for release

#629 Add ability to ignore hash check failures when downloading
  artifactory/services/download.go
  http/httpclient/client.go
Labels: safe to test, improvement

#633 Separate storage info calc and get
  README.md
  artifactory/emptymanager.go
  artifactory/manager.go
  artifactory/services/utils/aqlquerybuilder.go
  auth/cert/sslutils_default.go
  auth/cert/sslutils_windows.go
  go.mod
  go.sum
  tests/artifactorystorage_test.go
  utils/io/fileutils/files.go
Labels: safe to test, breaking change

#634 Rename IgnoreHashCheck to SkipChecksum
  artifactory/services/download.go
  http/httpclient/client.go
Labels: safe to test

#632 Correct segfault in example permission target code
  README.md
  tests/artifactorypermissiontarget_test.go
Labels: safe to test

#631 Encode properties in predictable order
  artifactory/services/utils/properties.go
  artifactory/services/utils/properties_test.go
Labels: safe to test, improvement

#635 Getting locked users and unlocking users in Artifactory
  README.md
  artifactory/emptymanager.go
  artifactory/manager.go
  artifactory/services/users.go
  tests/artifactoryusers_test.go
Labels: safe to test, new feature

#636 Expose get all groups to service managers
  artifactory/emptymanager.go
  artifactory/manager.go
Labels: bug, safe to test

#550 Unlabel safe to test automatically
  .github/workflows/tests.yml
Labels: ignore for release

#639 V1 - Update Go to 1.18
  appveyor.yml
  go.mod
  go.sum
Labels: safe to test, improvement

#637 Update Go to 1.18
  .github/workflows/analysis.yml
  .github/workflows/frogbot-fix.yml
  .github/workflows/frogbot-scan-pr.yml
  .github/workflows/tests.yml
  go.mod
  go.sum
Labels: improvement

#640 V1 - Update dependencies and add release notes generator
  .github/release.yml
  go.mod
  go.sum
Labels: improvement

#638 Breaking change: change property types in repository parameters structs
  artifactory/services/repository.go
  tests/artifactorylocalrepository_test.go
  tests/utils_test.go
Labels: breaking change

#642 Update dependencies
  .github/workflows/analysis.yml
  go.mod
  go.sum
Labels: improvement
