Repository jfrog/jfrog-client-go, pull requests merged in 2022-11, with the labels that each got.

#671 Return error on retry executor timeout
  distribution/services/deleteremote.go
  distribution/services/distribute.go
  utils/retryexecutor.go
  utils/retryexecutor_test.go
Labels: bug

#669 Upgrade v2 to GO 1.19
  .github/workflows/analysis.yml
  .github/workflows/frogbot-fix.yml
  .github/workflows/frogbot-scan-pr.yml
  .github/workflows/tests.yml
  artifactory/services/utils/releasebundleutils.go
  artifactory/services/utils/tests/files.go
  artifactory/services/utils/tests/xray/server.go
  auth/cert/loader.go
  auth/sshlogin.go
  go.mod
  go.sum
  http/httpclient/client.go
  http/httpclient/retryableconnection_test.go
  tests/artifactorydockerpromote_test.go
  tests/artifactorydownload_test.go
  tests/artifactoryexport_test.go
  tests/distribution_test.go
  utils/errorutils/errorutils.go
  utils/git.go
  utils/io/content/contentwriter_test.go
  utils/io/fileutils/archive.go
  utils/io/fileutils/files.go
  utils/io/fileutils/temp.go
  utils/utils.go
Labels: improvement

#664 Upgrade GO to 1.19
  appveyor.yml
  artifactory/services/utils/tests/files.go
  artifactory/services/utils/tests/xray/server.go
  auth/cert/loader.go
  auth/sshlogin.go
  go.mod
  go.sum
  http/httpclient/client.go
  http/httpclient/retryableconnection_test.go
  tests/artifactorydockerpromote_test.go
  tests/artifactorydownload_test.go
  tests/distribution_test.go
  tests/utils.go
  utils/errorutils/errorutils.go
  utils/git.go
  utils/io/content/contentwriter_test.go
  utils/io/fileutils/files.go
  utils/io/fileutils/temp.go
  utils/utils.go
Labels: safe to test, improvement

#675 Git LFS Fix - annotation tags unrecognized
  artifactory/services/gitlfsclean.go
Labels: bug

#674 Improve reference tokens handling
  auth/authutils.go
  auth/authutils_test.go
Labels: improvement

#676 New config accessor in DistributionServicesManager
  distribution/manager.go
Labels: improvement
