Repository jfrog/jfrog-client-go, pull requests merged in 2023-04, with the labels that each got.

#726 Upgrade go version in go.mod to 1.20
  .github/workflows/analysis.yml
  .github/workflows/frogbot-fix.yml
  .github/workflows/frogbot-scan-pr.yml
  .github/workflows/tests.yml
  go.mod
Labels: improvement

#725 Fix lint issues found by various go linters
  artifactory/services/createreplication.go
  artifactory/services/utils/aqlquerybuilder.go
  artifactory/services/utils/aqlquerybuilder_test.go
  artifactory/services/utils/artifactoryutils.go
  artifactory/services/utils/deleteutils.go
  artifactory/services/utils/deleteutils_test.go
  artifactory/services/utils/properties.go
  artifactory/services/utils/releasebundleutils.go
  artifactory/services/utils/repopathfile_test.go
  artifactory/services/utils/searchutil_test.go
  auth/cert/loader.go
  distribution/services/utils/distributionutils_test.go
  go.mod
  go.sum
  pipelines/services/run.go
  tests/artifactorypermissiontarget_test.go
  tests/artifactorysystem_test.go
  tests/utils_test.go
  tests/xrayscan_test.go
  tests/xraysummary_test.go
  utils/io/content/contentwriter.go
  utils/io/fileutils/files.go
  utils/utils.go
Labels: improvement

#731 Fix FindUpstream command logic
  go.mod
  go.sum
  utils/io/fileutils/files.go
Labels: ignore for release

#719 Add FlattenGraph for GraphNode
  xray/services/scan.go
  xray/services/scan_test.go
Labels: improvement

#732 Promote version to 1.28.1
  utils/utils.go
Labels: ignore for release

#733 Promote version to 1.28.1
  .github/workflows/analysis.yml
  .github/workflows/frogbot-fix.yml
  .github/workflows/frogbot-scan-pr.yml
  .github/workflows/tests.yml
  artifactory/services/createreplication.go
  artifactory/services/utils/aqlquerybuilder.go
  artifactory/services/utils/aqlquerybuilder_test.go
  artifactory/services/utils/artifactoryutils.go
  artifactory/services/utils/deleteutils.go
  artifactory/services/utils/deleteutils_test.go
  artifactory/services/utils/properties.go
  artifactory/services/utils/releasebundleutils.go
  artifactory/services/utils/repopathfile_test.go
  artifactory/services/utils/searchutil_test.go
  auth/cert/loader.go
  distribution/services/utils/distributionutils_test.go
  go.mod
  go.sum
  pipelines/services/run.go
  tests/artifactorypermissiontarget_test.go
  tests/artifactorysystem_test.go
  tests/utils_test.go
  tests/xrayscan_test.go
  tests/xraysummary_test.go
  utils/io/content/contentwriter.go
  utils/io/fileutils/files.go
  utils/utils.go
  xray/services/scan.go
  xray/services/scan_test.go
Labels: ignore for release

#737 Improve tests - retry mechanism to local artifactory install and pipelines pollingExecutor
  .github/workflows/tests.yml
  go.mod
  go.sum
  pipelines/services/run.go
  tests/pipelinesintegrations_test.go
  tests/pipelinessources_test.go
Labels: improvement

#738 Improve tests - retry mechanism to local artifactory install
  .github/workflows/tests.yml
Labels: ignore for release

#740 Added the Frogbot badge to the README
  README.md
Labels: improvement

#720 Add QueryParams to RemoteRepositoryBaseParams
  artifactory/services/remoterepository.go
Labels: improvement

#741 Improve Xray failure log when scan graph fails on Xray side
  go.mod
  go.sum
  utils/errorutils/errorutils.go
  xray/services/scan.go
Labels: improvement

#743 Audit - Log the list of flattened dependencies in debug
  utils/log/logger.go
  xray/services/scan.go
  xray/services/scan_test.go
Labels: improvement

#729 Support reference tokens
  access/manager.go
  access/services/accesstoken.go
  auth/authutils.go
  tests/accesstokens_test.go
  utils/antUtils.go
Labels: improvement

#745 Add Golangci-lint static code analysis and fix found issues
  .github/workflows/analysis.yml
  artifactory/services/discardBuilds.go
  artifactory/services/gitlfsclean.go
  artifactory/services/go/goutils.go
  artifactory/services/go/publish.go
  artifactory/services/security.go
  artifactory/services/utils/aqlquerybuilder.go
  artifactory/services/utils/aqlquerybuilder_test.go
  artifactory/services/utils/releasebundleutils.go
  artifactory/services/utils/searchutil.go
  artifactory/usage/reportusage_test.go
  auth/sshlogin.go
  go.mod
  go.sum
  http/httpclient/client.go
  http/httpclient/retryableconnection_test.go
  staticcheck.conf
  tests/artifactoryfederatedrepository_test.go
  tests/artifactorylocalrepository_test.go
  tests/artifactoryremoterepository_test.go
  tests/artifactoryreplication_test.go
  tests/artifactoryupload_test.go
  tests/artifactoryvirtualrepository_test.go
  tests/distribution_test.go
  tests/utils_test.go
  utils/antUtils_test.go
  utils/io/fileutils/files.go
  utils/io/fileutils/files_test.go
  utils/io/multifilereader.go
  utils/io/multifilereader_test.go
  utils/log/logger.go
  utils/parenthesesutils.go
  utils/tests/utils.go
  utils/utils.go
  utils/vcsdetails_test.go
  xray/services/scan.go
  xray/services/utils/watchbody.go
Labels: improvement

#750 Missing clean in GetLocalPathAndFile
  utils/io/fileutils/files.go
Labels: bug

#735 Improve unarchive inspection
  artifactory/services/download.go
  go.mod
  go.sum
  http/httpclient/client.go
  http/jfroghttpclient/client.go
  utils/archiveutils.go
  utils/io/fileutils/archive.go
  utils/io/fileutils/archive_test.go
  utils/io/fileutils/testdata/archives/softlink-rel.tar
  utils/io/fileutils/testdata/archives/softlink-rel.tar.gz
  utils/io/fileutils/testdata/archives/softlink-rel.zip
  utils/io/fileutils/testdata/archives/unix.tar
  utils/io/fileutils/testdata/archives/unix.tar.gz
  utils/io/fileutils/testdata/archives/unix.zip
  utils/io/fileutils/testdata/archives/win.tar
  utils/io/fileutils/testdata/archives/win.tar.gz
  utils/io/fileutils/testdata/archives/win.zip
  utils/io/fileutils/testdata/zipslip/abs.tar
  utils/io/fileutils/testdata/zipslip/abs.tar.gz
  utils/io/fileutils/testdata/zipslip/hardlink-tilde.tar
  utils/io/fileutils/testdata/zipslip/hardlink-tilde.tar.gz
  utils/io/fileutils/testdata/zipslip/rel.tar
  utils/io/fileutils/testdata/zipslip/rel.tar.gz
  utils/io/fileutils/testdata/zipslip/rel.zip
  utils/io/fileutils/testdata/zipslip/softlink-abs.tar
  utils/io/fileutils/testdata/zipslip/softlink-abs.tar.gz
  utils/io/fileutils/testdata/zipslip/softlink-abs.zip
  utils/io/fileutils/testdata/zipslip/softlink-rel.tar
  utils/io/fileutils/testdata/zipslip/softlink-rel.tar.gz
  utils/io/fileutils/testdata/zipslip/softlink-rel.zip
Labels: bug, improvement

#751 Add Frogbot schedule and remove frogbot-config.yml
  .frogbot/frogbot-config.yml
  .github/workflows/frogbot-scan-and-fix.yml
Labels: improvement

#755 Allow retrieving the temp dir base
  utils/io/fileutils/temp.go
Labels: ignore for release
