Repository jfrog/jfrog-client-go, pull requests merged in 2023-06, with the labels that each got.

#777 Update go-crypto version and fix RemoteRepo test
  go.mod
  go.sum
  tests/artifactoryremoterepository_test.go
Labels: ignore for release

#781 New UpdateRepositoryWithParams API
  artifactory/emptymanager.go
  artifactory/manager.go
  artifactory/services/federatedrepository.go
  artifactory/services/localrepository.go
  artifactory/services/remoterepository.go
  artifactory/services/repositories.go
  artifactory/services/repository.go
  artifactory/services/virtualrepository.go
  go.mod
  tests/artifactoryfederatedrepository_test.go
  tests/artifactorylocalrepository_test.go
  tests/artifactoryremoterepository_test.go
  tests/artifactoryvirtualrepository_test.go
  utils/archiveutils.go
Labels: new feature

#761 Support passing specific fields to AQL and fix wrongly asserted close() errors
  artifactory/services/utils/aqlquerybuilder.go
  artifactory/services/utils/searchutil.go
  artifactory/services/utils/specutils.go
Labels: new feature

#783 Fix flatten graph to cover node twice when needed.
  xray/services/scan.go
  xray/services/scan_test.go
  xray/services/utils/graph.go
Labels: bug

#778 Fix upload progress bar wrong values
  http/httpclient/client.go
  utils/io/progress.go
Labels: bug

#784 Unreleased bug progress bar value fix
  http/httpclient/client.go
Labels: ignore for release

#786 Improve GetRemoteFileDetails error response
  http/httpclient/client.go
Labels: ignore for release

#787 Flush the Content Writer before closing
  utils/io/content/contentwriter.go
Labels: improvement
