Repository jfrog/jfrog-client-go, pull requests merged in 2023-07, with the labels that each got.

#782 Support special characters in build scan parameters
  artifactory/services/utils/tests/xray/consts.go
  artifactory/services/utils/tests/xray/server.go
  tests/xray_test.go
  xray/manager.go
  xray/services/buildscan.go
Labels: bug

#785 Add web login service
  README.md
  access/manager.go
  access/services/login.go
  tests/accesslogin_test.go
Labels: ignore for release

#795 Fix wrongly errors return
  artifactory/services/delete.go
  artifactory/services/download.go
  artifactory/services/gitlfsclean.go
  artifactory/services/movecopy.go
  artifactory/services/upload.go
  artifactory/services/utils/deleteutils.go
  http/httpclient/client.go
  utils/git.go
  utils/io/content/contentreader.go
  utils/io/fileutils/files.go
  utils/io/fileutils/temp.go
  utils/io/fileutils/zip.go
Labels: ignore for release

#796 Improve upload detailed error response
  http/httpclient/client.go
Labels: improvement

#798 Align dev branch with master
  utils/utils.go
Labels: ignore for release

#794 Edit prepare exclusions pattern function
  artifactory/services/fspatterns/utils.go
  artifactory/services/upload.go
Labels: improvement

#799 Promoted version to 1.31.2
  utils/utils.go
Labels: ignore for release

#800 Clean relative paths in storage APIs
  artifactory/services/props.go
  artifactory/services/storage.go
Labels: bug, ignore for release

#801 General download progress bar shows incorrect values
  artifactory/services/download.go
Labels: bug
