Repository jfrog/jfrog-client-go, pull requests merged in 2023-11, with the labels that each got.

#852 Remove ecosystem usage report retry
  http/httpclient/client.go
  utils/usage/reportusage.go
Labels: improvement

#855 Promote build-info-go to v1.9.15
  go.mod
  go.sum
Labels: ignore for release

#856 Promoted version to 1.34.4
  utils/utils.go
Labels: ignore for release

#858 Add cdnRedirect flag to local and remote repositories base params
  artifactory/services/repository.go
Labels: improvement

#854 New AQL query for build-info json
  artifactory/services/utils/aqlquerybuilder.go
  artifactory/services/utils/aqlquerybuilder_test.go
  tests/artifactoryaql_test.go
  tests/jfrogclient_test.go
  tests/utils_test.go
  tests/xraybinmgr_test.go
  tests/xraywatch_test.go
Labels: improvement

#859 Promoted version to 1.34.5
  utils/utils.go
Labels: ignore for release

#862 Retry HTTP requests when receiving 429
  http/httpclient/client.go
Labels: improvement

#861 Support for Distribution path mapping with AQL
  artifactory/services/utils/specutils.go
  distribution/services/utils/distributionutils.go
  distribution/services/utils/releasebundlebody.go
  lifecycle/services/distribute.go
  tests/distribution_test.go
  utils/distribution/utils.go
  utils/distribution/utils_test.go
Labels: new feature
