Repository jfrog/jfrog-client-go, pull requests merged in 2023-01, with the labels that each got.

#690 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#691 New - JFrog Access ping service
  access/manager.go
  access/services/ping.go
  artifactory/services/dockerpromote.go
  artifactory/services/ping.go
  artifactory/services/props.go
  artifactory/services/storage.go
  artifactory/services/utils/searchutil.go
  distribution/services/create.go
  distribution/services/deletelocal.go
  distribution/services/deleteremote.go
  distribution/services/distribute.go
  distribution/services/getstatus.go
  distribution/services/setsigningkey.go
  distribution/services/sign.go
  distribution/services/update.go
  tests/accessping_test.go
  tests/jfrogclient_test.go
  tests/utils_test.go
Labels: improvement

#692 Always use AccessToken as 'Bearer' Authorization
  artifactory/services/remoterepository.go
  artifactory/services/system.go
  http/httpclient/client.go
  tests/artifactoryremoterepository_test.go
Labels: improvement

#693 New Projects and Repository services
  access/manager.go
  access/services/project.go
  artifactory/emptymanager.go
  artifactory/manager.go
  artifactory/services/repositories.go
  artifactory/services/upload.go
  artifactory/services/utils/artifactoryutils.go
  artifactory/services/utils/artifactoryutils_test.go
  tests/accessproject_test.go
Labels: improvement

#694 Add other_component_ids to /graph/scan API
  xray/services/scan.go
Labels: improvement

#605 Add git call to find .git directory for git worktrees
  utils/git.go
  utils/testdata/worktree/gitdata/COMMIT_EDITMSG
  utils/testdata/worktree/gitdata/HEAD
  utils/testdata/worktree/gitdata/config
  utils/testdata/worktree/gitdata/description
  utils/testdata/worktree/gitdata/index
  utils/testdata/worktree/gitdata/logs/HEAD
  utils/testdata/worktree/gitdata/objects/0e/58052bba5f3c26e64c68925d8a27f820dc6a15
  utils/testdata/worktree/gitdata/objects/61/98a6294722fdc75a570aac505784d2ec0d1818
  utils/testdata/worktree/gitdata/objects/79/31df4bd53290e8178a245d01bec34a245f3226
  utils/testdata/worktree/gitdata/objects/90/d9cc9bf05666e6910bdfa4f914e96c706454c3
  utils/testdata/worktree/gitdata/objects/b4/f457c219dbb3517be908d4e70f0ada2fd8b8f9
  utils/testdata/worktree/gitdata/objects/e6/9de29bb2d1d6434b8b29ae775ad8c2e48c5391
  utils/testdata/worktree/gitdata/refs/heads/master
  utils/testdata/worktree/worktree_repo/gitWorktreeData
  utils/tests/utils.go
  utils/vcsdetails_test.go
Labels: bug

#696 New Projects and Repository services - Readme
  README.md
  utils/git.go
Labels: ignore for release

#699 Move Access tests to local artifactory
  .github/workflows/tests.yml
  tests/utils_test.go
  utils/tests/utils.go
Labels: ignore for release

#700 Fix and improve repositories and distribution tests
  tests/artifactoryfederatedrepository_test.go
  tests/artifactorylocalrepository_test.go
  tests/artifactoryremoterepository_test.go
  tests/artifactorysecurity_test.go
  tests/artifactorystorage_test.go
  tests/artifactoryvirtualrepository_test.go
  tests/distribution_test.go
  tests/pipelines_test.go
  tests/pipelinesintegrations_test.go
  tests/pipelinesrun_test.go
  tests/pipelinessources_test.go
  tests/xraywatch_test.go
Labels: ignore for release

#698 Add static analysis to test files
  .github/workflows/analysis.yml
  auth/authutils_test.go
Labels: ignore for release

#701 Add util to extract the subject from JWT tokens
  auth/authutils.go
  auth/authutils_test.go
Labels: improvement

#702 Improve create access token error log
  access/services/accesstoken.go
Labels: improvement

#703 Handle API key used as Access Token
  auth/authutils.go
  http/httpclient/client.go
  utils/retryexecutor.go
Labels: improvement
