Repository jfrog/jfrog-client-go, pull requests merged in 2023-08, with the labels that each got.

#804 Promote to v1.31.4
  go.mod
  go.sum
  utils/utils.go
Labels: ignore for release

#808 Fix typo when using an API key as access token
  http/httpclient/client.go
Labels: ignore for release

#813 Fix gosec issues
  artifactory/services/gitlfsclean_test.go
  artifactory/services/go/go_test.go
  pipelines/services/run.go
  pipelines/services/syncstatus.go
Labels: ignore for release

#814 Promote version to v1.31.5
  go.mod
  go.sum
  utils/utils.go
Labels: ignore for release

#807 New usage reporting methods
  access/services/login.go
  artifactory/services/delete.go
  artifactory/services/discardBuilds.go
  artifactory/services/distribute.go
  artifactory/services/dockerpromote.go
  artifactory/services/download.go
  artifactory/services/go/publish.go
  artifactory/services/movecopy.go
  artifactory/services/ping.go
  artifactory/services/promote.go
  artifactory/services/props.go
  artifactory/services/readfile.go
  artifactory/services/security.go
  artifactory/services/storage.go
  artifactory/services/upload.go
  artifactory/services/utils/artifactoryutils.go
  artifactory/services/xrayscan.go
  artifactory/usage/reportusage.go
  artifactory/usage/reportusage_test.go
  lifecycle/services/delete.go
  lifecycle/services/operation.go
  lifecycle/services/status.go
  tests/artifactoryupload_test.go
  utils/usage/reportusage.go
  utils/usage/reportusage_test.go
  utils/utils.go
  xray/usage/reportusage.go
  xray/usage/reportusage_test.go
Labels: improvement

#816 Promoted version to 1.31.6
  utils/utils.go
Labels: ignore for release

#797 Support Lifecycle Release Bundle Distribute
  README.md
  distribution/manager.go
  distribution/services/deleteremote.go
  distribution/services/distribute.go
  distribution/services/getstatus.go
  distribution/services/utils/distributionutils.go
  distribution/services/utils/distributionutils_test.go
  distribution/services/utils/releasebundlebody.go
  lifecycle/manager.go
  lifecycle/services/distribute.go
  tests/distribution_test.go
  tests/utils_test.go
  utils/distribution/distribute.go
  utils/distribution/specutils.go
  utils/distribution/utils.go
  utils/distribution/utils_test.go
Labels: breaking change, new feature

#815 Improve Audit and Scan performance for large projects
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
  .github/workflows/frogbot-scan-pull-request.yml
  .github/workflows/frogbot-scan-repository.yml
  .github/workflows/tests.yml
  go.mod
  go.sum
  utils/antutils.go
  utils/antutils_test.go
  utils/io/fileutils/files.go
  utils/io/fileutils/files_test.go
  utils/tests/utils.go
  utils/vcsdetails_test.go
  xray/services/scan.go
  xray/services/scan_test.go
  xray/services/utils/graph.go
Labels: improvement
