Repository jfrog/jfrog-client-go, pull requests merged in 2023-10, with the labels that each got.

#835 Fix latest build not found handling
  artifactory/services/utils/artifactoryutils.go
Labels: bug

#822 Support Platform Access Token
  README.md
  access/services/accesstoken.go
  auth/authutils.go
  tests/accesstokens_test.go
Labels: breaking change, improvement

#837 Support overall request timeout in all services
  README.md
  access/manager.go
  artifactory/manager.go
  auth/servicedetails.go
  config/config.go
  config/configbuilder.go
  distribution/manager.go
  http/httpclient/clientBuilder.go
  http/jfroghttpclient/clientbuilder.go
  lifecycle/manager.go
  pipelines/manager.go
  tests/timeout_test.go
  utils/io/httputils/httpclient.go
  utils/tests/utils.go
  xray/manager.go
Labels: new feature

#838 Updated dependencies and release version
  go.mod
  go.sum
  utils/utils.go
Labels: ignore for release

#839 Fix panic when build doesn't exist
  artifactory/services/utils/artifactoryutils.go
Labels: bug

#840 Promoted version to 1.34.1
  utils/utils.go
Labels: ignore for release

#841 Fix error handling in git utils
  utils/git.go
Labels: bug

#842 Improve JFrog platform get version error logs
  artifactory/services/system.go
  distribution/services/version.go
  http/httpclient/client.go
  pipelines/services/system.go
  xray/services/entitlements.go
  xray/services/scan.go
  xray/services/version.go
Labels: improvement

#844 Promote version to v1.34.2
  utils/utils.go
Labels: ignore for release

#847 Bypass archive inspection is ignored
  .github/workflows/analysis.yml
  artifactory/services/download.go
Labels: bug

#848 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#849 Promote version to 1.34.3
  go.mod
  utils/utils.go
Labels: ignore for release
