Repository jfrog/jfrog-client-go, pull requests merged in 2023-03, with the labels that each got.

#715 Improve usage report error logs
  artifactory/services/upload.go
  artifactory/usage/reportusage.go
  go.mod
  go.sum
  http/httpclient/client.go
Labels: improvement

#714 Added source deletion check before creating source in pipeline run tests
  README.md
  pipelines/manager.go
  pipelines/services/sources.go
  tests/pipelinesrun_test.go
  tests/pipelinessources_test.go
Labels: ignore for release

#718 Fix possible progress bar NPE on archive upload
  artifactory/services/upload.go
Labels: bug

#716 Refactor ANT pattern logic
  utils/antUtils.go
  utils/antUtils_test.go
  utils/utils.go
  utils/utils_test.go
Labels: improvement

#721 Fix CLA trigger
  .github/workflows/cla.yml
  go.mod
  go.sum
Labels: ignore for release

#722 Update cla.yml
  .github/workflows/cla.yml
Labels: ignore for release
