Repository jfrog/jfrog-client-go, pull requests merged in 2023-09, with the labels that each got.

#775 New report scan of licenses and violations
  README.md
  artifactory/services/utils/tests/xray/consts.go
  artifactory/services/utils/tests/xray/server.go
  tests/xrayreport_test.go
  xray/manager.go
  xray/services/report.go
Labels: new feature

#823 Add Xray Source Control Service
  artifactory/services/utils/tests/xray/consts.go
  artifactory/services/utils/tests/xray/server.go
  tests/xrayreport_test.go
  xray/manager.go
  xray/services/report.go
  xray/services/scan.go
Labels: improvement

#825 Promote version to 1.32.0
  utils/utils.go
Labels: ignore for release

#826 Handle custom Xray urls in Xsc
  xray/services/scan.go
Labels: bug

#827 Promote version to 1.32.1
  utils/utils.go
Labels: ignore for release

#829 Hide Xray min version report usage warning log
  artifactory/usage/reportusage.go
  artifactory/usage/reportusage_test.go
  utils/utils_test.go
  xray/usage/reportusage.go
  xray/usage/reportusage_test.go
Labels: ignore for release

#830 Reduce refreshing threshold for platform access token
  auth/authutils.go
  auth/servicedetails.go
Labels: improvement

#818 Support lifecycle release bundle remote delete
  README.md
  lifecycle/manager.go
  lifecycle/services/delete.go
  lifecycle/services/distribute.go
Labels: new feature

#833 Update min Xray usage version
  xray/usage/reportusage.go
  xray/usage/reportusage_test.go
Labels: ignore for release

#834 Convert remote repository numeric fields to pointers to avoid omitting
  access/services/accesstoken.go
  artifactory/services/remoterepository.go
  go.mod
  go.sum
  tests/accessproject_test.go
  tests/accesstokens_test.go
  tests/artifactoryfederatedrepository_test.go
  tests/artifactoryfederation_test.go
  tests/artifactorygroup_test.go
  tests/artifactorylocalrepository_test.go
  tests/artifactorypermissiontarget_test.go
  tests/artifactoryremoterepository_test.go
  tests/artifactoryusers_test.go
  tests/artifactoryvirtualrepository_test.go
  tests/utils_test.go
  tests/xraypolicy_test.go
  tests/xrayreport_test.go
  tests/xraywatch_test.go
  utils/utils.go
Labels: bug
