Repository jfrog/jfrog-client-go, pull requests merged in 2024-04, with the labels that each got.

#928 New XSC analytics metrics capabilities.
  .github/workflows/tests.yml
  README.md
  tests/utils_test.go
  tests/xsc_test.go
  tests/xscanalyticsevent_test.go
  utils/utils.go
  utils/utils_test.go
  xray/manager.go
  xsc/auth/xscdetails.go
  xsc/manager.go
  xsc/services/analytics.go
  xsc/services/version.go
Labels: improvement

#932 New XSC log errors capabilities
  tests/xsclogerrorevent_test.go
  xsc/manager.go
  xsc/services/logerrorevent.go
Labels: improvement

#921 Artifactory Release Lifecycle Management - Add Import bundle function
  README.md
  artifactory/emptymanager.go
  artifactory/manager.go
  artifactory/services/releasebundle.go
  tests/releasebundle_test.go
Labels: new feature

#935 XRAY-20331: Add CWE and CWE Details in Vulnerabilities model
  xray/services/scan.go
Labels: improvement

#939 Promote version to v1.40.1
  go.mod
  go.sum
  utils/utils.go
Labels: ignore for release

#936 Support providing chunk size in multi part upload
  README.md
  artifactory/services/upload.go
  artifactory/services/utils/multipartupload.go
  artifactory/services/utils/multipartupload_test.go
  artifactory/services/utils/storageutils.go
  artifactory/services/utils/storageutils_test.go
Labels: improvement

#937 Support attaching Uber Trace ID to every request
  http/httpclient/client.go
Labels: improvement
