Repository jfrog/jfrog-client-go, pull requests merged in 2024-01, with the labels that each got.

#884 Graph Scan internal API - New GraphNode field added to GraphNode
  xray/services/utils/graph.go
Labels: improvement

#885 Promote to 1.35.6
  go.mod
  go.sum
  tests/utils_test.go
  utils/utils.go
Labels: ignore for release

#780 New Terraform & PHP Composer repositories support
  artifactory/services/localrepository.go
  artifactory/services/remoterepository.go
  artifactory/services/virtualrepository.go
  tests/artifactoryremoterepository_test.go
  tests/artifactoryvirtualrepository_test.go
  tests/utils_test.go
Labels: new feature

#887 Add trailing slash if needed on SetUrl method
  .github/workflows/analysis.yml
  .github/workflows/tests.yml
  access/services/project.go
  artifactory/services/download.go
  artifactory/services/fspatterns/utils.go
  artifactory/services/go/publish.go
  artifactory/services/upload.go
  artifactory/services/utils/aqlquerybuilder.go
  artifactory/services/utils/artifactoryutils.go
  artifactory/services/utils/searchutil.go
  artifactory/usage/reportusage.go
  auth/authutils.go
  auth/servicedetails.go
  distribution/services/deleteremote.go
  go.mod
  go.sum
  http/httpclient/client.go
  http/httpclient/clientBuilder.go
  tests/artifactoryremoterepository_test.go
  tests/artifactoryupload_test.go
  tests/artifactoryvirtualrepository_test.go
  utils/io/content/contentreader.go
  utils/io/fileutils/temp.go
  utils/usage/reportusage.go
  xray/services/summary.go
  xray/services/utils/watchbody.go
  xray/usage/reportusage.go
Labels: improvement

#888 Fix after Changes to MSI
  xray/services/scan.go
Labels: ignore for release

#891 Add multi_scan_id to scan params for sca scan flow
  xray/services/scan.go
Labels: improvement

#892 Promote version to '1.36.1'
  utils/utils.go
  xray/services/scan.go
Labels: ignore for release
