Repository jfrog/jfrog-client-go, pull requests merged in 2024-08, with the labels that each got.

#988 Avoid panic on temp file deletion
  artifactory/services/download.go
  artifactory/services/fspatterns/utils.go
  artifactory/services/upload.go
  artifactory/services/utils/multipartupload.go
  artifactory/services/utils/searchutil.go
  go.mod
  go.sum
  utils/io/fileutils/files.go
  utils/io/fileutils/temp.go
  utils/io/fileutils/temp_test.go
Labels: bug

#994 Generate symlinks in test instead of using testdata
  utils/io/fileutils/files_test.go
  utils/io/fileutils/testdata/dirsymlinks/d1/File_F1
  utils/io/fileutils/testdata/dirsymlinks/d1/linktoparent
  utils/io/fileutils/testdata/dirsymlinks/d2/d1link
Labels: ignore for release

#993 Multipart upload - Repo key and repo path encoding
  artifactory/services/utils/multipartupload.go
  artifactory/services/utils/multipartupload_test.go
Labels: bug

#995 Release 1.43.2
  go.mod
  go.sum
  utils/utils.go
Labels: ignore for release

#996 Unite http content type header code
  access/services/accesstoken.go
  access/services/invite.go
  access/services/login.go
  artifactory/services/discardBuilds.go
  artifactory/services/distribute.go
  artifactory/services/dockerpromote.go
  artifactory/services/export.go
  artifactory/services/federation.go
  artifactory/services/permissiontarget.go
  artifactory/services/props.go
  artifactory/services/repository.go
  artifactory/services/upload.go
  artifactory/services/utils/artifactoryutils.go
  artifactory/services/xrayscan.go
  artifactory/usage/reportusage.go
  distribution/services/create.go
  distribution/services/deletelocal.go
  distribution/services/deleteremote.go
  distribution/services/setsigningkey.go
  distribution/services/sign.go
  distribution/services/update.go
  evidence/services/operation.go
  lifecycle/services/delete.go
  lifecycle/services/operation.go
  pipelines/services/run.go
  tests/utils_test.go
  utils/distribution/distribute.go
  utils/io/content/contentreader.go
  utils/io/content/contentwriter.go
  utils/io/httputils/httpclient.go
  xray/services/binMgr.go
  xray/services/buildscan.go
  xray/services/enrich.go
  xray/services/ignorerule.go
  xray/services/policy.go
  xray/services/report.go
  xray/services/scan.go
  xray/services/summary.go
  xray/services/watch.go
  xray/usage/reportusage.go
Labels: improvement

#997 Adding Metadata Service Manager
  README.md
  metadata/auth/metadatadetails.go
  metadata/manager.go
  metadata/services/graphql.go
  metadata/services/graphql_test.go
  tests/timeout_test.go
Labels: new feature

#991 Secret Token Validation
  README.md
  artifactory/services/utils/tests/xray/consts.go
  artifactory/services/utils/tests/xray/server.go
  tests/xrayjasconfig_test.go
  xray/manager.go
  xray/services/jasconfig.go
Labels: improvement

#1003 Fix missing checksum header bug
  artifactory/services/upload.go
Labels: bug

#1005 Improve token and build info service errors
  artifactory/services/buildinfo.go
  artifactory/services/security.go
  artifactory/services/system.go
  tests/artifactoryctx_test.go
Labels: improvement

#1006 Add and use a new IsPathAccessible API before accessing the .git dir
  utils/io/fileutils/files.go
  utils/io/fileutils/files_test.go
  utils/vcsdetails.go
Labels: bug

#1010 Fixing failing TestXrayWatch testcases
  tests/xraywatch_test.go
Labels: ignore for release

#1002 New service for centralized config profile
  README.md
  tests/testdata/configprofile/configProfileExample.json
  tests/xscconfigprofile_test.go
  tests/xsclogerrorevent_test.go
  xsc/manager.go
  xsc/services/profile.go
Labels: new feature

#1011 Promote to v1.45.0
  utils/utils.go
Labels: ignore for release

#1007 Add project key to GetAllRepositoriesFiltered
  README.md
  artifactory/services/repositories.go
  artifactory/services/repositories_test.go
Labels: new feature

#1013 Release 1.46.0
  go.mod
  go.sum
  utils/utils.go
Labels: ignore for release

#1012 Add ClearProgress() and increase minimal file size to show archive progressbar
  artifactory/services/upload.go
  utils/io/progress.go
Labels: improvement
