Repository jfrog/jfrog-client-go, pull requests merged in 2024-03, with the labels that each got.

#918 Tweak multipart upload polling
  artifactory/services/utils/multipartupload.go
  artifactory/services/utils/multipartupload_test.go
Labels: ignore for release

#919 Fix false positive ZipSlip when an archive starts with dot
  go.mod
  go.sum
Labels: bug

#920 Multipart upload - Fix empty nodeId response in completeMultipartUpload
  artifactory/services/utils/multipartupload.go
  artifactory/services/utils/multipartupload_test.go
Labels: ignore for release

#922 Mock dry run deletion success
  artifactory/services/delete.go
Labels: improvement

#911 Artifactory Release Lifecycle Management - Support release bundles deletion
  README.md
  distribution/services/distribute.go
  lifecycle/lifecycle_test.go
  lifecycle/manager.go
  lifecycle/services/delete.go
  lifecycle/services/distribute.go
  lifecycle/services/promote.go
  lifecycle/services/status.go
  utils/distribution/distribute.go
Labels: new feature

#913 Artifactory Release Lifecycle Management - Support release bundle distribution by project
  distribution/manager.go
  distribution/services/distribute.go
  distribution/services/getstatus.go
  lifecycle/manager.go
  lifecycle/services/delete.go
  lifecycle/services/distribute.go
  lifecycle/services/operation.go
  lifecycle/services/status.go
  tests/distribution_test.go
  utils/distribution/distribute.go
  utils/distribution/utils.go
Labels: new feature

#924 Promote version to 1.38.0
  go.mod
  go.sum
  utils/utils.go
Labels: ignore for release

#925 Simplify defer closer funcs
  artifactory/services/movecopy.go
  go.mod
  go.sum
  utils/git.go
  utils/utils.go
Labels: ignore for release

#917 Artifactory Release Lifecycle Management - Add Export bundle function
  README.md
  go.mod
  go.sum
  lifecycle/manager.go
  lifecycle/services/create.go
  lifecycle/services/export.go
  lifecycle/services/operation.go
  lifecycle/services/promote.go
Labels: new feature

#929 Update dependencies
  .github/workflows/analysis.yml
  go.mod
  go.sum
Labels: ignore for release

#931 expose dry run mode value of lifecycle manager
  lifecycle/manager.go
Labels: ignore for release
