Repository jfrog/jfrog-client-go, pull requests merged in 2024-12, with the labels that each got.

#1051 Improve error message for unsupported protocol scheme with URL context
  http/httpclient/client.go
Labels: improvement

#1057 Add implementations for new API: config profile with repository context
  tests/xsc_test.go
  tests/xscanalyticsevent_test.go
  tests/xscconfigprofile_test.go
  tests/xsclogerrorevent_test.go
  xray/services/xsc/xsc.go
  xsc/manager.go
  xsc/service.go
  xsc/services/profile.go
Labels: ignore for release

#1060 Internal API - Visibility System support
  artifactory/usage/call_home.go
  artifactory/usage/call_home_test.go
  go.mod
  go.sum
  jfconnect/auth/jfconnectdetails.go
  jfconnect/manager.go
  jfconnect/services/metrics.go
  utils/utils.go
Labels: improvement

#1061 Internal API - Visibility System fix & improvements
  jfconnect/manager.go
  jfconnect/services/metrics.go
Labels: bug

#1062 Internal API - New `product_version` field added to the Visibility Metric
  jfconnect/services/metrics.go
Labels: improvement

#1063 Internal - Remove the Call Home version validation
  artifactory/usage/call_home.go
Labels: improvement
