Repository jfrog/jfrog-client-go, pull requests merged in 2024-05, with the labels that each got.

#947 Classifier property added to GraphNode struct
  xray/services/utils/graph.go
Labels: improvement

#948 Support Started Status for Release Bundle Creation
  lifecycle/services/status.go
Labels: bug

#950 Remove redundant space in logs and update dependencies
  artifactory/services/download.go
  artifactory/services/upload.go
  go.mod
  go.sum
Labels: improvement

#951 Fix username extraction on OIDC tokens with a group scope
  auth/authutils.go
  auth/authutils_test.go
Labels: bug

#933 Bugfix for the creation of a Violation Report
  xray/services/report.go
Labels: bug

#952 Promote version to v1.40.2
  utils/utils.go
Labels: ignore for release

#954 `gofrog` Dependency Updated to v1.7.2
  go.mod
  go.sum
  utils/archiveutils.go
Labels: ignore for release

#957 Add client for Evidence service
  README.md
  evidence/auth/evidencedetails.go
  evidence/evidence_test.go
  evidence/manager.go
  evidence/services/create.go
  evidence/services/operation.go
  tests/timeout_test.go
Labels: new feature
