Repository jfrog/jfrog-client-go, pull requests merged in 2024-09, with the labels that each got.

#1015 Add "Fail Fast" flag for Upload Service
  artifactory/emptymanager.go
  artifactory/manager.go
  artifactory/services/upload.go
  artifactory/services/utils/multipartupload.go
  utils/utils.go
Labels: improvement

#1017 Update dependencies
  artifactory/services/utils/multipartupload.go
  go.mod
  go.sum
  utils/utils.go
Labels: ignore for release

#1018 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#1016 Remove redundant search log
  artifactory/services/utils/searchutil.go
  go.mod
  go.sum
  utils/utils.go
Labels: improvement

#1019 Handle archive upload general progress bar counter incrementation
  artifactory/services/download.go
  artifactory/services/upload.go
  artifactory/usage/reportusage.go
  go.mod
  go.sum
Labels: improvement

#1021 Add failFast flag to UploadFiles(), UploadFilesWithSummary()
  README.md
  artifactory/emptymanager.go
  artifactory/manager.go
Labels: breaking change

#1023 Add uploadServiceOptions to UploadFiles service
  .github/workflows/tests.yml
  README.md
  artifactory/emptymanager.go
  artifactory/manager.go
Labels: breaking change

#1024 Upgrade to v1.47.0
  go.mod
  go.sum
  utils/utils.go
Labels: ignore for release

#1025 Make failFast upload service param public
  README.md
  artifactory/manager.go
Labels: improvement
