Repository jfrog/jfrog-client-go, pull requests merged in 2024-02, with the labels that each got.

#893 Artifactory Release Lifecycle Management - Modify release bundle promotion properties
  README.md
  lifecycle/manager.go
  lifecycle/services/create.go
  lifecycle/services/delete.go
  lifecycle/services/operation.go
  lifecycle/services/promote.go
Labels: breaking change, improvement

#895 Artifactory Release Lifecycle Management - Add include dependencies option to release bundle creation
  lifecycle/services/create.go
Labels: new feature

#902 Fix static code analysis
  auth/authutils_test.go
  auth/cert/loader.go
Labels: ignore for release

#899 Upload empty archive when all upload files were filtered out
  artifactory/services/fspatterns/utils.go
  artifactory/services/upload.go
  go.mod
  go.sum
Labels: improvement

#898 Expose XSC git info API
  README.md
  artifactory/services/utils/tests/xray/consts.go
  artifactory/services/utils/tests/xray/server.go
  tests/xray_test.go
  tests/xrayreport_test.go
  tests/xrayscan_test.go
  tests/xraysummary_test.go
  xray/manager.go
  xray/services/scan.go
Labels: improvement

#889 Add missing Terraform repository methods and tests
  README.md
  artifactory/services/federatedrepository.go
  artifactory/services/remoterepository.go
  tests/artifactoryfederatedrepository_test.go
  tests/artifactorylocalrepository_test.go
  tests/artifactoryremoterepository_test.go
  tests/artifactoryvirtualrepository_test.go
Labels: improvement

#906 Fix Master-Dev conflicts
  utils/utils.go
Labels: ignore for release

#904 Promote version to 1.37.0
  go.mod
  go.sum
  utils/utils.go
Labels: ignore for release

#907 Merge changes to master
  README.md
  artifactory/services/federatedrepository.go
  artifactory/services/fspatterns/utils.go
  artifactory/services/remoterepository.go
  artifactory/services/upload.go
  artifactory/services/utils/tests/xray/consts.go
  artifactory/services/utils/tests/xray/server.go
  auth/authutils_test.go
  auth/cert/loader.go
  go.mod
  go.sum
  lifecycle/manager.go
  lifecycle/services/create.go
  lifecycle/services/delete.go
  lifecycle/services/operation.go
  lifecycle/services/promote.go
  pipelines/manager.go
  pipelines/services/integration.go
  tests/artifactoryfederatedrepository_test.go
  tests/artifactorylocalrepository_test.go
  tests/artifactoryremoterepository_test.go
  tests/artifactoryvirtualrepository_test.go
  tests/pipelinesintegrations_test.go
  tests/xray_test.go
  tests/xrayreport_test.go
  tests/xrayscan_test.go
  tests/xraysummary_test.go
  utils/utils.go
  xray/manager.go
  xray/services/scan.go
Labels: ignore for release

#909 Promote version to 1.37.1
  go.mod
  go.sum
  utils/utils.go
Labels: ignore for release

#900 Artifactory Multi-Part Upload support
  .github/workflows/tests.yml
  README.md
  artifactory/manager.go
  artifactory/services/download.go
  artifactory/services/fspatterns/utils.go
  artifactory/services/upload.go
  artifactory/services/utils/multipartupload.go
  artifactory/services/utils/multipartupload_test.go
  artifactory/services/utils/storageutils.go
  go.mod
  go.sum
  http/httpclient/client.go
  tests/artifactorymultipartupload_test.go
  tests/jfrogclient_test.go
  tests/utils_test.go
  utils/io/fileutils/files.go
  utils/io/progress.go
  utils/retryexecutor.go
Labels: ignore for release

#903 Artifactory Release Lifecycle Management - Support creation by artifacts and sync for distribution
  README.md
  lifecycle/manager.go
  lifecycle/services/create.go
  lifecycle/services/distribute.go
  lifecycle/services/status.go
Labels: improvement

#910 Artifactory Release Lifecycle Management - get lifecycle release bundle specification
  README.md
  distribution/services/getstatus.go
  lifecycle/lifecycle_test.go
  lifecycle/manager.go
  lifecycle/services/status.go
Labels: new feature

#914 Add file info rest API for artifactory
  artifactory/emptymanager.go
  artifactory/manager.go
  artifactory/services/storage.go
  artifactory/services/utils/storageutils.go
  tests/artifactorystorage_test.go
Labels: new feature
