Repository jfrog/jfrog-client-go, pull requests merged in 2024-07, with the labels that each got.

#964 Fix http client redirect race condition
  .github/workflows/tests.yml
  artifactory/services/download.go
  artifactory/services/upload.go
  artifactory/services/utils/specutils.go
  go.mod
  go.sum
  http/httpclient/client.go
  http/httpclient/retryableconnection.go
  utils/io/content/contentreader.go
  utils/io/content/contentwriter.go
  utils/tests/utils.go
Labels: bug

#969 Remove the label from the download progress indicator struct initialization
  http/httpclient/client.go
Labels: improvement

#970 Improve ResultItem code
  artifactory/services/delete.go
  artifactory/services/download.go
  artifactory/services/movecopy.go
  artifactory/services/upload.go
  artifactory/services/utils/deleteutils.go
  artifactory/services/utils/deleteutils_test.go
  artifactory/services/utils/searchutil.go
Labels: ignore for release

#961 SBOM ingestion
  README.md
  artifactory/services/utils/tests/xray/consts.go
  artifactory/services/utils/tests/xray/server.go
  tests/xrayenrich_test.go
  xray/manager.go
  xray/services/enrich.go
  xray/services/scan.go
  xray/services/utils/pollingaction.go
Labels: new feature

#975 Fix symlink handling for upload with size limit
  artifactory/services/fspatterns/utils.go
Labels: safe to test, ignore for release

#976 Promote version to 1.42.0
  go.mod
  go.sum
  utils/utils.go
Labels: ignore for release

#977 Handle ignored errors and avoid panic
  artifactory/services/upload.go
  artifactory/services/utils/multipartupload.go
  http/httpclient/client.go
  utils/git.go
  utils/io/content/contentwriter.go
  utils/io/fileutils/files.go
  utils/io/fileutils/zip.go
Labels: improvement

#967 Xray Ignore rules support
  README.md
  tests/jfrogclient_test.go
  tests/utils_test.go
  tests/xrayignorerule_test.go
  xray/manager.go
  xray/services/ignorerule.go
  xray/services/utils/ignorerulebody.go
Labels: new feature

#981 Upgrade depedencies
  go.mod
  go.sum
  utils/utils.go
Labels: ignore for release

#982 Improve download/upload logs and progress bar
  artifactory/services/download.go
  artifactory/services/upload.go
  artifactory/services/utils/multipartupload.go
  http/httpclient/client.go
Labels: safe to test

#984 Remove JFrog Pipelines tests
  .github/workflows/tests.yml
Labels: ignore for release

#980 Multipart Upload: Remove the redirect to specific Artifactory node
  artifactory/services/utils/multipartupload.go
  artifactory/services/utils/multipartupload_test.go
Labels: improvement

#983 Add repo field to docker build-info artifacts
  artifactory/services/utils/searchutil.go
  go.mod
  go.sum
Labels: improvement

#986 Revert MinSplitSize renaming
  artifactory/services/download.go
Labels: ignore for release

#985 Populate original deployment field for npm and terraform artifacts
  artifactory/services/utils/resultutils.go
Labels: improvement

#987 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#989 Multipart upload - Set the the checksum deploy token
  artifactory/services/upload.go
  artifactory/services/utils/artifactoryutils.go
  artifactory/services/utils/multipartupload.go
  artifactory/services/utils/multipartupload_test.go
Labels: improvement

#990 Promoted version to 1.43.1
  go.mod
  go.sum
  utils/utils.go
Labels: ignore for release
