Repository jfrog/jfrog-client-go, pull requests merged in 2024-11, with the labels that each got.

#1036 Remove remaining temp file after Artifactory download
  artifactory/services/download.go
  artifactory/services/utils/searchutil.go
  http/httpclient/client.go
Labels: bug

#1041 Upgrade build-info-go to v1.10.4
  go.mod
  go.sum
  utils/utils.go
Labels: improvement

#1043 Upgrade build-info-go
  go.mod
  go.sum
  utils/utils.go
Labels: improvement

#1042 Improve upload archive progress bar counter
  artifactory/services/upload.go
  go.mod
  go.sum
  tests/artifactoryremoterepository_test.go
Labels: improvement

#1044 Add Artifactory API to get package artifact lead file
  README.md
  artifactory/emptymanager.go
  artifactory/manager.go
  artifactory/services/packages.go
  go.sum
  tests/artifactoryPackage_test.go
  tests/jfrogclient_test.go
  tests/utils_test.go
Labels: new feature

#1045 Promote version to v1.48.0
  go.sum
  utils/utils.go
Labels: ignore for release

#1046 Transition Xsc to Xray
  artifactory/services/utils/tests/xray/consts.go
  artifactory/services/utils/tests/xray/server.go
  tests/xrayscan_test.go
  xray/manager.go
  xray/services/scan.go
  xray/services/xsc/xsc.go
  xsc/manager.go
  xsc/service.go
  xsc/services/analytics.go
  xsc/services/logerrorevent.go
  xsc/services/profile.go
  xsc/services/utils/utils.go
  xsc/services/utils/utils_test.go
  xsc/services/version.go
Labels: ignore for release

#1048 Change XSC in Xray min version to 3.107.13
  xray/services/xsc/xsc.go
  xsc/manager.go
  xsc/services/utils/utils.go
  xsc/services/utils/utils_test.go
Labels: improvement

#1049 Promote to v1.48.1
  utils/utils.go
Labels: ignore for release

#1050 No MSI No XSC
  xray/services/scan.go
Labels: bug

#1047 Fix the "Get Distribution Export" polling logic
  lifecycle/services/export.go
Labels: bug
