Repository jfrog/jfrog-client-go, pull requests merged in 2025-05, with the labels that each got.

#1110 RTDEV-56127 - Support annotate command for release bundle
  README.md
  lifecycle/lifecycle_test.go
  lifecycle/manager.go
  lifecycle/services/annotate.go
Labels: new feature

#1116 bump version to v`1.53.0`
  go.mod
  go.sum
  utils/utils.go
Labels: ignore for release

#1119 Add project key param to Xray api
  README.md
  utils/utils.go
  xray/manager.go
  xray/services/buildscan.go
  xray/services/entitlements.go
  xray/services/scan.go
  xray/services/xsc/xsc.go
  xsc/services/analytics.go
  xsc/services/logerrorevent.go
  xsc/services/profile.go
  xsc/services/watch.go
Labels: improvement

#1123 Promote version to `1.53.1`
  utils/utils.go
Labels: ignore for release
