Repository jfrog/jfrog-client-go, pull requests merged in 2025-02, with the labels that each got.

#1081 Add Build Runs API
  README.md
  artifactory/emptymanager.go
  artifactory/manager.go
  artifactory/services/buildinfo.go
  artifactory/services/utils/artifactoryutils.go
  go.mod
  go.sum
  tests/artifactorybuilds_test.go
Labels: new feature

#1082 Promote version v1.50.0
  go.mod
  go.sum
  utils/utils.go
Labels: ignore for release

#1083 Support for Build info overwrite for a given build name and number
  README.md
  artifactory/buildinfo/config.go
  artifactory/emptymanager.go
  artifactory/manager.go
  artifactory/services/buildinfo.go
  go.mod
  go.sum
  tests/artifactorybuilds_test.go
Labels: feature request

#1087 Fix all Xsc tests to align Migration to Xray + Fix Watches failing tests
  tests/utils_test.go
  tests/xraywatch_test.go
  tests/xsc_test.go
  tests/xscanalyticsevent_test.go
  tests/xscconfigprofile_test.go
  tests/xsclogerrorevent_test.go
Labels: ignore for release

#1091 Promote version 1.51.0
  go.mod
  go.sum
  utils/utils.go
Labels: ignore for release

#1093 Fix spelling
  http/httpclient/client.go
Labels: ignore for release
